version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn blogproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    expose:
      - 8000
#    ports:
#      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=django_project_db_user
#      - POSTGRES_PASSWORD=django_project_db_password
#      - POSTGRES_DB=django_project_dev
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume: